[default_session]
disable_startup_command = true


[[session]]
name = "Static_boot.dev"
path = "~/workspace/github.com/jakobboedker/StaticSite_Generator/"
startup_command = "ls -a"


[[session]]
name = "dotfiles"
path = "~/dotfiles/"
startup_command = "ls -a"

[[session]]
name = "constelia"
path = "~/x/"
startup_command = "ls -a"

[[session]]
name = "cpu & GPU temp"
path = "~"
startup_command = "watch -n 2 sensors"





